# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_app.managers
import main_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('group_number', models.CharField(max_length=15, verbose_name='group number')),
                ('mobile_phone', models.CharField(max_length=40, unique=True, verbose_name='mobile phone')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', main_app.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=254, unique=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('killers', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('\u041d\u043e\u0432\u0430\u044f', '\u041d\u043e\u0432\u0430\u044f'), ('\u0417\u0430\u043a\u043e\u043d\u0447\u0438\u043b\u0430\u0441\u044c', '\u0417\u0430\u043a\u043e\u043d\u0447\u0438\u043b\u0430\u0441\u044c'), ('\u0418\u0434\u0435\u0442 \u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044f', '\u0418\u0434\u0435\u0442 \u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044f')], default='\u041d\u043e\u0432\u0430\u044f', max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('group_number', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='game/')),
                ('status', models.CharField(choices=[('\u0416\u0438\u0432', '\u0416\u0438\u0432'), ('\u041c\u0435\u0440\u0442\u0432', '\u041c\u0435\u0440\u0442\u0432')], default='\u0416\u0438\u0432', max_length=5)),
                ('personal_code', models.CharField(default=main_app.models.generate_code, max_length=6, unique=True)),
                ('victim_code', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('kills', models.IntegerField(default=0)),
                ('participants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main_app.Game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
