# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 23:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('\u041d\u043e\u0432\u0430\u044f', '\u041d\u043e\u0432\u0430\u044f'), ('\u0418\u0434\u0435\u0442 \u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044f', '\u0418\u0434\u0435\u0442 \u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044f'), ('\u0417\u0430\u043a\u043e\u043d\u0447\u0438\u043b\u0430\u0441\u044c', '\u0417\u0430\u043a\u043e\u043d\u0447\u0438\u043b\u0430\u0441\u044c')], default='\u041d\u043e\u0432\u0430\u044f', max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='photo',
            field=models.ImageField(upload_to=main_app.models.get_file_name),
        ),
        migrations.AlterField(
            model_name='participants',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
