# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170911_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='victim_mobile_phone',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('\u041d\u043e\u0432\u0430\u044f \u0418\u0433\u0440\u0430', '\u041d\u043e\u0432\u0430\u044f \u0418\u0433\u0440\u0430'), ('\u0418\u0434\u0435\u0442 \u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044f', '\u0418\u0434\u0435\u0442 \u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044f'), ('\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044f \u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0430', '\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044f \u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0430'), ('\u0418\u0433\u0440\u0430 \u041d\u0430\u0447\u0430\u043b\u0430\u0441\u044c', '\u0418\u0433\u0440\u0430 \u041d\u0430\u0447\u0430\u043b\u0430\u0441\u044c'), ('\u0418\u0433\u0440\u0430 \u0417\u0430\u043a\u043e\u043d\u0447\u0438\u043b\u0430\u0441\u044c', '\u0418\u0433\u0440\u0430 \u0417\u0430\u043a\u043e\u043d\u0447\u0438\u043b\u0430\u0441\u044c')], default='\u041d\u043e\u0432\u0430\u044f \u0418\u0433\u0440\u0430', max_length=24, unique=True),
        ),
    ]
