# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20170912_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='personal_code',
            field=models.CharField(default=main_app.models.generate_code, max_length=6),
        ),
    ]
